# Generated by Django 2.0.6 on 2018-06-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choic_text',
            field=models.CharField(max_length=201),
        ),
    ]
